#!/bin/sh

# post-receive hook for this repo. This script is executed whenever new code
# is successfully pushed to this repo. In this case we're invoking the node-deploy
# script as root and passing through the name of the application.

APP_NAME="proxy-node-app" sudo sh /var/node/node-deploy